---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name1 | quote }}
spec:
  type: {{ .Values.service.type1 }}
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name2 | quote }}
spec:
  type: {{ .Values.service.type2 }}
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}


