# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: cartservice

service:
  type: ClusterIP
  port: 7070
  name: cartservice
  targetport: 7070

spec:
  serviceAccountName: default
  terminationGracePeriodSeconds: 5

securityContext1:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext2:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true

container: 
  name: server

env:
  name: REDIS_ADDR
  value: "redis-cart:6379"

requests:
  cpu: 200m
  memory: 64Mi

limits:
  cpu: 300m
  memory: 128Mi

probe:
  initialDelaySeconds: 15
  periodSeconds: 10

