# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: loadgenerator

spec:
  serviceAccountName: default
  terminationGracePeriodSeconds: 5

securityContext1:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext2:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true

container: 
  name: main

env:
  name1: FRONTEND_ADDR
  value1: "frontend:80"
  name2: USERS
  value2: "10"

requests:
  cpu: 300m
  memory: 256Mi

limits:
  cpu: 500m
  memory: 512Mi
