apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
  ports:
  - name: grpc
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}

